# Generated by Django 4.2 on 2025-05-14 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField(default=0.0)),
                ('competitor_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
