# Generated by Django 4.2 on 2025-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='po_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
