# Generated by Django 4.2 on 2025-06-20 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchaseorders_po_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordItem',
            fields=[
                ('sales_item_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField(default=1)),
                ('unit_price_at_sale', models.FloatField(default=0.0)),
                ('discount_applied', models.FloatField(default=0.0)),
                ('promotion_marker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_record_items', to='api.products')),
            ],
            options={
                'verbose_name_plural': 'Sales Record Items',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='api.customer')),
            ],
            options={
                'verbose_name_plural': 'Sales Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='SalesRecords',
        ),
        migrations.AddField(
            model_name='salesrecorditem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.salestransaction'),
        ),
    ]
