# Generated by Django 4.2 on 2025-05-14 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchaseorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('sales_record_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('quantity_sold', models.IntegerField(default=1)),
                ('unit_price_at_sale', models.FloatField(default=0.0)),
                ('discount_applied', models.FloatField(default=0.0)),
                ('promotion_marker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='api.products')),
            ],
            options={
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('po_item_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ordered_quantity', models.IntegerField(default=1)),
                ('received_quantity', models.IntegerField(default=0)),
                ('unit_cost_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='api.products')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorders')),
            ],
            options={
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
    ]
