# Generated by Django 4.2 on 2025-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_salesrecords_purchaseorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Received', 'Received')], default='Ordered', max_length=50),
        ),
    ]
