# Generated by Django 4.2 on 2025-06-12 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchaseorders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('forecast_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('forecast_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('forecast_value', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('method_used', models.CharField(choices=[('historical_avg', 'Historical Average'), ('trending', 'Trending Analysis'), ('seasonal', 'Seasonal Pattern'), ('hybrid', 'Hybrid Algorithm'), ('manual_override', 'Manual Override')], default='historical_avg', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='api.products')),
            ],
            options={
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['-forecast_date'],
                'unique_together': {('product', 'forecast_date', 'forecast_period')},
            },
        ),
    ]
